# Generated by Django 3.2.3 on 2023-03-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('isVerified', models.BooleanField(default=False)),
                ('otpToVerify', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'authDB',
            },
        ),
        migrations.CreateModel(
            name='bottlesDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('bottleID', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'bottlesDB',
            },
        ),
    ]
