# Generated by Django 4.1.3 on 2023-03-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loggerDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('bottleID', models.CharField(max_length=150)),
                ('timeStamp', models.DateTimeField(auto_now=True)),
                ('measurement', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'loggerDB',
            },
        ),
    ]
