# Generated by Django 4.1.3 on 2023-03-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggerdb',
            name='timeStamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
